# Generated by Django 2.0.7 on 2018-07-16 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KauaiSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('content', models.CharField(max_length=360)),
                ('url', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Announcements',
            new_name='Announcement',
        ),
        migrations.RenameModel(
            old_name='Messsage',
            new_name='Message',
        ),
    ]
